//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teuerungsportal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teuerungsportal.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Übersicht zur Teuerung in Österreich.
        /// </summary>
        internal static string appInfo {
            get {
                return ResourceManager.GetString("appInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teuerungsportal.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artikelnummer.
        /// </summary>
        internal static string articleNumber {
            get {
                return ResourceManager.GetString("articleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marke.
        /// </summary>
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie eine Gesamtübersicht aller indexierten Kategorien. Klicken Sie einfach auf eine Kategorie um in die entsprechende Übersicht zu gelangen..
        /// </summary>
        internal static string categoriesInfo {
            get {
                return ResourceManager.GetString("categoriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können Sie alle Infos zu der aktuellen Kategorie sehen. Außerdem sehen Sie aktuelle Statistiken und kürzliche Änderungen..
        /// </summary>
        internal static string categoryInfo {
            get {
                return ResourceManager.GetString("categoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string changeDateTime {
            get {
                return ResourceManager.GetString("changeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramm.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Diagramm zeigt die Preissteigerungen der letzten 30 Tage und soll visualisieren, ob sich Unternehmem absprechen und gewisse Produkte an den gleichen Tagen angepasst werden..
        /// </summary>
        internal static string chartInfo {
            get {
                return ResourceManager.GetString("chartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zitatrecht.
        /// </summary>
        internal static string citation {
            get {
                return ResourceManager.GetString("citation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Platform dient einzig und allein der Information und stützt sich auf das österreichische Zitatrecht, da keine geschützten Werke in Bild- oder Tonform von den Seiten Dritter gespeichert, abgefragt oder verbreitet werden. Ausschließlich der Preis, als auch der Artikelname und die Produktnummer werden unter den folgenden Sachverhalt verwendet: 1. Der Zweck des Preiszitats ist die Protokollierung und Visualisierung; 2. Als Quelle wird ein direkter Link zum Produkt eingebunden; 3. Der Umfang umfasst aussch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string citationText {
            get {
                return ResourceManager.GetString("citationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wir verwenden Cookies.
        /// </summary>
        internal static string cookieConsent {
            get {
                return ResourceManager.GetString("cookieConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aber nur welche, die wirklich für Ihre aktuelle Sitzung benötigt werden. Keine Tracker, keine Google Fonts, oder ähnliches. .
        /// </summary>
        internal static string cookieConsentText {
            get {
                return ResourceManager.GetString("cookieConsentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        internal static string currLang {
            get {
                return ResourceManager.GetString("currLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senkungen.
        /// </summary>
        internal static string decreases {
            get {
                return ResourceManager.GetString("decreases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisverlauf.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string impress {
            get {
                return ResourceManager.GetString("impress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Seite dient allein dem gemeinnützigen Zweck und verfolgt keine unternehmerische gewinnorientierte Leistung. Es werden keine Cookies oder andere personenbezogenen Daten gespeichert. Alle Daten dienen nur der Information und stehen mit keiner der Online Shops in Verbindung. Fehler der Daten unter Vorbehalt..
        /// </summary>
        internal static string impressContent {
            get {
                return ResourceManager.GetString("impressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erhöhungen.
        /// </summary>
        internal static string increases {
            get {
                return ResourceManager.GetString("increases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftungshinweis.
        /// </summary>
        internal static string liability {
            get {
                return ResourceManager.GetString("liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich..
        /// </summary>
        internal static string liabilityText {
            get {
                return ResourceManager.GetString("liabilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadaten.
        /// </summary>
        internal static string metadata {
            get {
                return ResourceManager.GetString("metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Elternkategorie.
        /// </summary>
        internal static string noParentCategory {
            get {
                return ResourceManager.GetString("noParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Preisänderungen.
        /// </summary>
        internal static string noRecentPriceChanges {
            get {
                return ResourceManager.GetString("noRecentPriceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell gab es noch keine Preisänderungen..
        /// </summary>
        internal static string noRecentPriceChangesText {
            get {
                return ResourceManager.GetString("noRecentPriceChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Unterkategorien.
        /// </summary>
        internal static string noSubCategories {
            get {
                return ResourceManager.GetString("noSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell gibt es noch keine Unterkategorien.
        /// </summary>
        internal static string noSubCategoriesText {
            get {
                return ResourceManager.GetString("noSubCategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider gab es in den letzten 24 Stunden keine Preisänderungen, die für KonsumentInnen erfreulich wären..
        /// </summary>
        internal static string noTopChanges {
            get {
                return ResourceManager.GetString("noTopChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juhu! Keine Teuerungen in den letzten 24 Stunden..
        /// </summary>
        internal static string noWorstChanges {
            get {
                return ResourceManager.GetString("noWorstChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Online Shop.
        /// </summary>
        internal static string onlineShopLink {
            get {
                return ResourceManager.GetString("onlineShopLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elternkategorie.
        /// </summary>
        internal static string parentCategory {
            get {
                return ResourceManager.GetString("parentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performanz.
        /// </summary>
        internal static string performance {
            get {
                return ResourceManager.GetString("performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es ist leider bekannt, dass die Performanz dieser Seite nicht die Beste ist. Das hat den Grund, dass die Infrastruktur, damit sie gut skalieren kann, relativ teuer ist. Falls Sie das Projekt gut finden und direkt unterstützen möchten, können Sie gerne auf PayPal eine kleine Spende hinterlassen..
        /// </summary>
        internal static string performanceText {
            get {
                return ResourceManager.GetString("performanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Änderung.
        /// </summary>
        internal static string priceChange {
            get {
                return ResourceManager.GetString("priceChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisänderungen.
        /// </summary>
        internal static string priceChanges {
            get {
                return ResourceManager.GetString("priceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können Sie alle Infos zum aktuellen Produkt sehen. Außerdem sehen Sie aktuelle Statistiken und kürzliche Änderungen..
        /// </summary>
        internal static string productInfo {
            get {
                return ResourceManager.GetString("productInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkte.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisänderungen.
        /// </summary>
        internal static string recentPriceChanges {
            get {
                return ResourceManager.GetString("recentPriceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäft.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können Sie alle Infos zum aktuellen Geschäft sehen. Außerdem sehen Sie aktuelle Statistiken und kürzliche Änderungen..
        /// </summary>
        internal static string storeInfo {
            get {
                return ResourceManager.GetString("storeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäfte.
        /// </summary>
        internal static string stores {
            get {
                return ResourceManager.GetString("stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie eine Gesamtübersicht aller gefilterten Geschäfte. Klicken Sie einfach auf ein Geschäft um in die entsprechende Übersicht zu gelangen..
        /// </summary>
        internal static string storesInfo {
            get {
                return ResourceManager.GetString("storesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterkategorien.
        /// </summary>
        internal static string subCategories {
            get {
                return ResourceManager.GetString("subCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützen.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützer.
        /// </summary>
        internal static string supporters {
            get {
                return ResourceManager.GetString("supporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie eine Liste aller Unterstützer:innen. Tausend Dank an alle die dieses Projekt monetär unterstützen und so diese Platform am Leben erhalten..
        /// </summary>
        internal static string supportersText {
            get {
                return ResourceManager.GetString("supportersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Unterstützer:innen werden im Impressum erwähnt..
        /// </summary>
        internal static string supportInfo {
            get {
                return ResourceManager.GetString("supportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heutige Preisänderungen.
        /// </summary>
        internal static string todayChanges {
            get {
                return ResourceManager.GetString("todayChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Größte Änderungen.
        /// </summary>
        internal static string topChanges {
            get {
                return ResourceManager.GetString("topChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Übersicht zeigt die bis zu 5 größten Preisänderungen der letzten 24 Stunden..
        /// </summary>
        internal static string topChangesInfo {
            get {
                return ResourceManager.GetString("topChangesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkategorisiert.
        /// </summary>
        internal static string uncategorized {
            get {
                return ResourceManager.GetString("uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unkategorisierte Produkte.
        /// </summary>
        internal static string uncategorizedProducts {
            get {
                return ResourceManager.GetString("uncategorizedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstüzten Sie das Teuerungsportal, indem Sie unkategorisierte Produkte kategorisieren..
        /// </summary>
        internal static string uncategorizedProductsInfo {
            get {
                return ResourceManager.GetString("uncategorizedProductsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzlich Willkommen im österreichischen Teuerungsportal. Bitte beachten Sie, dass es sich hier um ein Hobbyprojekt handelt, welches die Daten direkt aus den österreichischen Handelsgewerben extrahiert. Analysieren Sie selbst Ihre Lieblingsprodukte und verfolgen Sie die aktuelle Teuerung in Echtzeit..
        /// </summary>
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlechteste Änderungen.
        /// </summary>
        internal static string worstChanges {
            get {
                return ResourceManager.GetString("worstChanges", resourceCulture);
            }
        }
    }
}
