//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teuerungsportal.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Teuerungsportal.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        internal static string categoriesInfo {
            get {
                return ResourceManager.GetString("categoriesInfo", resourceCulture);
            }
        }
        
        internal static string subCategories {
            get {
                return ResourceManager.GetString("subCategories", resourceCulture);
            }
        }
        
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        internal static string appInfo {
            get {
                return ResourceManager.GetString("appInfo", resourceCulture);
            }
        }
        
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        internal static string noRecentPriceChanges {
            get {
                return ResourceManager.GetString("noRecentPriceChanges", resourceCulture);
            }
        }
        
        internal static string noRecentPriceChangesText {
            get {
                return ResourceManager.GetString("noRecentPriceChangesText", resourceCulture);
            }
        }
        
        internal static string changeDateTime {
            get {
                return ResourceManager.GetString("changeDateTime", resourceCulture);
            }
        }
        
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        internal static string recentPriceChanges {
            get {
                return ResourceManager.GetString("recentPriceChanges", resourceCulture);
            }
        }
        
        internal static string categoryInfo {
            get {
                return ResourceManager.GetString("categoryInfo", resourceCulture);
            }
        }
        
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        internal static string productInfo {
            get {
                return ResourceManager.GetString("productInfo", resourceCulture);
            }
        }
        
        internal static string stores {
            get {
                return ResourceManager.GetString("stores", resourceCulture);
            }
        }
        
        internal static string storesInfo {
            get {
                return ResourceManager.GetString("storesInfo", resourceCulture);
            }
        }
        
        internal static string storeInfo {
            get {
                return ResourceManager.GetString("storeInfo", resourceCulture);
            }
        }
        
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        internal static string metadata {
            get {
                return ResourceManager.GetString("metadata", resourceCulture);
            }
        }
        
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        internal static string articleNumber {
            get {
                return ResourceManager.GetString("articleNumber", resourceCulture);
            }
        }
        
        internal static string onlineShopLink {
            get {
                return ResourceManager.GetString("onlineShopLink", resourceCulture);
            }
        }
        
        internal static string parentCategory {
            get {
                return ResourceManager.GetString("parentCategory", resourceCulture);
            }
        }
        
        internal static string noParentCategory {
            get {
                return ResourceManager.GetString("noParentCategory", resourceCulture);
            }
        }
        
        internal static string noSubCategories {
            get {
                return ResourceManager.GetString("noSubCategories", resourceCulture);
            }
        }
        
        internal static string noSubCategoriesText {
            get {
                return ResourceManager.GetString("noSubCategoriesText", resourceCulture);
            }
        }
        
        internal static string uncategorized {
            get {
                return ResourceManager.GetString("uncategorized", resourceCulture);
            }
        }
        
        internal static string uncategorizedProducts {
            get {
                return ResourceManager.GetString("uncategorizedProducts", resourceCulture);
            }
        }
        
        internal static string uncategorizedProductsInfo {
            get {
                return ResourceManager.GetString("uncategorizedProductsInfo", resourceCulture);
            }
        }
        
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        internal static string chartInfo {
            get {
                return ResourceManager.GetString("chartInfo", resourceCulture);
            }
        }
        
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        internal static string impress {
            get {
                return ResourceManager.GetString("impress", resourceCulture);
            }
        }
        
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        internal static string impressContent {
            get {
                return ResourceManager.GetString("impressContent", resourceCulture);
            }
        }
        
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        internal static string todayChanges {
            get {
                return ResourceManager.GetString("todayChanges", resourceCulture);
            }
        }
        
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
        
        internal static string performance {
            get {
                return ResourceManager.GetString("performance", resourceCulture);
            }
        }
        
        internal static string performanceText {
            get {
                return ResourceManager.GetString("performanceText", resourceCulture);
            }
        }
        
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        internal static string supportInfo {
            get {
                return ResourceManager.GetString("supportInfo", resourceCulture);
            }
        }
        
        internal static string supporters {
            get {
                return ResourceManager.GetString("supporters", resourceCulture);
            }
        }
        
        internal static string supportersText {
            get {
                return ResourceManager.GetString("supportersText", resourceCulture);
            }
        }
        
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        internal static string liability {
            get {
                return ResourceManager.GetString("liability", resourceCulture);
            }
        }
        
        internal static string liabilityText {
            get {
                return ResourceManager.GetString("liabilityText", resourceCulture);
            }
        }
        
        internal static string citation {
            get {
                return ResourceManager.GetString("citation", resourceCulture);
            }
        }
        
        internal static string citationText {
            get {
                return ResourceManager.GetString("citationText", resourceCulture);
            }
        }
        
        internal static string cookieConsent {
            get {
                return ResourceManager.GetString("cookieConsent", resourceCulture);
            }
        }
        
        internal static string cookieConsentText {
            get {
                return ResourceManager.GetString("cookieConsentText", resourceCulture);
            }
        }
        
        internal static string currLang {
            get {
                return ResourceManager.GetString("currLang", resourceCulture);
            }
        }
        
        internal static string topChanges {
            get {
                return ResourceManager.GetString("topChanges", resourceCulture);
            }
        }
        
        internal static string worstChanges {
            get {
                return ResourceManager.GetString("worstChanges", resourceCulture);
            }
        }
        
        internal static string topChangesInfo {
            get {
                return ResourceManager.GetString("topChangesInfo", resourceCulture);
            }
        }
        
        internal static string noTopChanges {
            get {
                return ResourceManager.GetString("noTopChanges", resourceCulture);
            }
        }
        
        internal static string noWorstChanges {
            get {
                return ResourceManager.GetString("noWorstChanges", resourceCulture);
            }
        }
        
        internal static string priceChanges {
            get {
                return ResourceManager.GetString("priceChanges", resourceCulture);
            }
        }
        
        internal static string increases {
            get {
                return ResourceManager.GetString("increases", resourceCulture);
            }
        }
        
        internal static string decreases {
            get {
                return ResourceManager.GetString("decreases", resourceCulture);
            }
        }
        
        internal static string priceChange {
            get {
                return ResourceManager.GetString("priceChange", resourceCulture);
            }
        }
        
        internal static string priceHistory {
            get {
                return ResourceManager.GetString("priceHistory", resourceCulture);
            }
        }
        
        internal static string inflation {
            get {
                return ResourceManager.GetString("inflation", resourceCulture);
            }
        }
        
        internal static string categorize {
            get {
                return ResourceManager.GetString("categorize", resourceCulture);
            }
        }
        
        internal static string addCategory {
            get {
                return ResourceManager.GetString("addCategory", resourceCulture);
            }
        }
        
        internal static string createCategoryInfo {
            get {
                return ResourceManager.GetString("createCategoryInfo", resourceCulture);
            }
        }
        
        internal static string categoryName {
            get {
                return ResourceManager.GetString("categoryName", resourceCulture);
            }
        }
        
        internal static string createCategory {
            get {
                return ResourceManager.GetString("createCategory", resourceCulture);
            }
        }
        
        internal static string categoryNameInfo {
            get {
                return ResourceManager.GetString("categoryNameInfo", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string newProducts {
            get {
                return ResourceManager.GetString("newProducts", resourceCulture);
            }
        }
        
        internal static string moreInfos {
            get {
                return ResourceManager.GetString("moreInfos", resourceCulture);
            }
        }
        
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        internal static string thisWeek {
            get {
                return ResourceManager.GetString("thisWeek", resourceCulture);
            }
        }
        
        internal static string thisMonth {
            get {
                return ResourceManager.GetString("thisMonth", resourceCulture);
            }
        }
        
        internal static string thisYear {
            get {
                return ResourceManager.GetString("thisYear", resourceCulture);
            }
        }
        
        internal static string allTime {
            get {
                return ResourceManager.GetString("allTime", resourceCulture);
            }
        }
        
        internal static string grouped {
            get {
                return ResourceManager.GetString("grouped", resourceCulture);
            }
        }
        
        internal static string ascending {
            get {
                return ResourceManager.GetString("ascending", resourceCulture);
            }
        }
        
        internal static string descending {
            get {
                return ResourceManager.GetString("descending", resourceCulture);
            }
        }
        
        internal static string darkTheme {
            get {
                return ResourceManager.GetString("darkTheme", resourceCulture);
            }
        }
        
        internal static string lightTheme {
            get {
                return ResourceManager.GetString("lightTheme", resourceCulture);
            }
        }
        
        internal static string priceChangeDate {
            get {
                return ResourceManager.GetString("priceChangeDate", resourceCulture);
            }
        }
        
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        internal static string quoteSource {
            get {
                return ResourceManager.GetString("quoteSource", resourceCulture);
            }
        }
        
        internal static string quoteText {
            get {
                return ResourceManager.GetString("quoteText", resourceCulture);
            }
        }
        
        internal static string goodbyeHeader {
            get {
                return ResourceManager.GetString("goodbyeHeader", resourceCulture);
            }
        }
        
        internal static string goodbyeInitial {
            get {
                return ResourceManager.GetString("goodbyeInitial", resourceCulture);
            }
        }
        
        internal static string goodbyeTextA {
            get {
                return ResourceManager.GetString("goodbyeTextA", resourceCulture);
            }
        }
        
        internal static string goodbyeTextB {
            get {
                return ResourceManager.GetString("goodbyeTextB", resourceCulture);
            }
        }
        
        internal static string goodbyeTextC {
            get {
                return ResourceManager.GetString("goodbyeTextC", resourceCulture);
            }
        }
        
        internal static string goodbyeTextD {
            get {
                return ResourceManager.GetString("goodbyeTextD", resourceCulture);
            }
        }
        
        internal static string goodbyeThanks {
            get {
                return ResourceManager.GetString("goodbyeThanks", resourceCulture);
            }
        }
    }
}
