//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teuerungsportal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teuerungsportal.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Übersicht zur Teuerung in Österreich.
        /// </summary>
        internal static string appInfo {
            get {
                return ResourceManager.GetString("appInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teuerungsportal.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorien.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie eine Gesamtübersicht aller indexierten Kategorien. Klicken Sie einfach auf eine Kategorie um in die entsprechende Übersicht zu gelangen..
        /// </summary>
        internal static string categoriesInfo {
            get {
                return ResourceManager.GetString("categoriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können Sie alle Infos zu der aktuellen Kategorie sehen. Außerdem sehen Sie aktuelle Statistiken und kürzliche Änderungen..
        /// </summary>
        internal static string categoryInfo {
            get {
                return ResourceManager.GetString("categoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string changeDateTime {
            get {
                return ResourceManager.GetString("changeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisverlauf.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Preisänderungen.
        /// </summary>
        internal static string noRecentPriceChanges {
            get {
                return ResourceManager.GetString("noRecentPriceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell gab es noch keine Preisänderungen..
        /// </summary>
        internal static string noRecentPriceChangesText {
            get {
                return ResourceManager.GetString("noRecentPriceChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier können Sie alle Infos zum aktuellen Produkt sehen. Außerdem sehen Sie aktuelle Statistiken und kürzliche Änderungen..
        /// </summary>
        internal static string productInfo {
            get {
                return ResourceManager.GetString("productInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkt.
        /// </summary>
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preisänderungen.
        /// </summary>
        internal static string recentPriceChanges {
            get {
                return ResourceManager.GetString("recentPriceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäft.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäfte.
        /// </summary>
        internal static string stores {
            get {
                return ResourceManager.GetString("stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier finden Sie eine Gesamtübersicht aller gefilterten Geschäfte. Klicken Sie einfach auf ein Geschäft um in die entsprechende Übersicht zu gelangen..
        /// </summary>
        internal static string storesInfo {
            get {
                return ResourceManager.GetString("storesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterkategorien.
        /// </summary>
        internal static string subCategories {
            get {
                return ResourceManager.GetString("subCategories", resourceCulture);
            }
        }
    }
}
