//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teuerungsportal.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teuerungsportal.Resources.Language.en", typeof(Language_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your overview of inflation in Austria..
        /// </summary>
        internal static string appInfo {
            get {
                return ResourceManager.GetString("appInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inflation Portal.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Number.
        /// </summary>
        internal static string articleNumber {
            get {
                return ResourceManager.GetString("articleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string categories {
            get {
                return ResourceManager.GetString("categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find a complete overview of all indexed categories. Simply click on a category to access the corresponding overview..
        /// </summary>
        internal static string categoriesInfo {
            get {
                return ResourceManager.GetString("categoriesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all information about the current category. Additionally, you can view current statistics and recent changes..
        /// </summary>
        internal static string categoryInfo {
            get {
                return ResourceManager.GetString("categoryInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string changeDateTime {
            get {
                return ResourceManager.GetString("changeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        internal static string chart {
            get {
                return ResourceManager.GetString("chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagram illustrates the price increases over the past 30 days and aims to visualize whether companies are coordinating and adjusting certain products on the same days..
        /// </summary>
        internal static string chartInfo {
            get {
                return ResourceManager.GetString("chartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price History.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string impress {
            get {
                return ResourceManager.GetString("impress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page serves solely for nonprofit purposes and does not pursue any profit-oriented business performance. No cookies or other personally identifiable information are stored. All data is for informational purposes only and is not associated with any online shops. Data errors are possible and subject to change..
        /// </summary>
        internal static string impressContent {
            get {
                return ResourceManager.GetString("impressContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Data.
        /// </summary>
        internal static string metadata {
            get {
                return ResourceManager.GetString("metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Parent Category.
        /// </summary>
        internal static string noParentCategory {
            get {
                return ResourceManager.GetString("noParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent price changes.
        /// </summary>
        internal static string noRecentPriceChanges {
            get {
                return ResourceManager.GetString("noRecentPriceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There have been no price changes so far..
        /// </summary>
        internal static string noRecentPriceChangesText {
            get {
                return ResourceManager.GetString("noRecentPriceChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Subcategories.
        /// </summary>
        internal static string noSubCategories {
            get {
                return ResourceManager.GetString("noSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no sub categories.
        /// </summary>
        internal static string noSubCategoriesText {
            get {
                return ResourceManager.GetString("noSubCategoriesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the Online Shop.
        /// </summary>
        internal static string onlineShopLink {
            get {
                return ResourceManager.GetString("onlineShopLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Category.
        /// </summary>
        internal static string parentCategory {
            get {
                return ResourceManager.GetString("parentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string performance {
            get {
                return ResourceManager.GetString("performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, it is known that the performance of this site is not the best. The reason for this is that the infrastructure, in order to scale well, is relatively expensive. If you like the project and would like to support it directly, you are welcome to leave a small donation on PayPal..
        /// </summary>
        internal static string performanceText {
            get {
                return ResourceManager.GetString("performanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all information about the current product. Additionally, you can view current statistics and recent changes..
        /// </summary>
        internal static string productInfo {
            get {
                return ResourceManager.GetString("productInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Changes.
        /// </summary>
        internal static string recentPriceChanges {
            get {
                return ResourceManager.GetString("recentPriceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can see all information about the current store. Additionally, you can view current statistics and recent changes..
        /// </summary>
        internal static string storeInfo {
            get {
                return ResourceManager.GetString("storeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        internal static string stores {
            get {
                return ResourceManager.GetString("stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can find a complete overview of all crawled stores. Simply click on a store to access the corresponding overview..
        /// </summary>
        internal static string storesInfo {
            get {
                return ResourceManager.GetString("storesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories.
        /// </summary>
        internal static string subCategories {
            get {
                return ResourceManager.GetString("subCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All supporters are mentioned in the impress..
        /// </summary>
        internal static string supportInfo {
            get {
                return ResourceManager.GetString("supportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todays Changes.
        /// </summary>
        internal static string todayChanges {
            get {
                return ResourceManager.GetString("todayChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized.
        /// </summary>
        internal static string uncategorized {
            get {
                return ResourceManager.GetString("uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncategorized Products.
        /// </summary>
        internal static string uncategorizedProducts {
            get {
                return ResourceManager.GetString("uncategorizedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help the Teuerungsportal by categorizing products, which are currently uncategorized..
        /// </summary>
        internal static string uncategorizedProductsInfo {
            get {
                return ResourceManager.GetString("uncategorizedProductsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        internal static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Austrian Inflation Portal. Please note that this is a hobby project that directly extracts data from Austrian trade industries. Analyze your favorite products yourself and track the current inflation in real time..
        /// </summary>
        internal static string welcomeText {
            get {
                return ResourceManager.GetString("welcomeText", resourceCulture);
            }
        }
    }
}
